language: node_js
node_js:
- '6'
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: c0YRbtuVWVDTC1OOSblQEM9xrdJ7+selioxO5BHydcyvbZOKxVb/Yxdv5L7SnzLU9Cl5sSNwXYuVA32J+jz6iTMoX7l13OBzS5mcHZT9+OGe5beAjP4rZEB5uhddpNUqGS6y8ZHA51wTc7y3wgcyzoFGD4C3Iv9RfwjNoNLzuHLaHelgGVVxGg1qw+ByGmX3ccYDB1gC6Yy44BVpJxAiBphI/+FUsUD0c4NrOYl1TDtVqlKw0GnpY/cByDpGmX47Y84N8iR+F2whEeLnDPokQv6wnCri99fzZY5qNfEiMl9sPEjUHoSgv/NP0nexrPOvpWYQQu8w3Lh1/MyUi5f3qD7eFCY0klp6V3VbudLYhfTjWMI+KvIfTl7MtF+D28rAJLqBrlhPGzXt198l1o+IO2cGfUIp4YIsy97IJDPR6OXQncWMyv7asdaMIkDozQR8HR3vm9koKH/Brq06cLXdSjXipbydCPeggAvl7iYYQSPekWjH5uM4oZ1UGdlv1QkDoeNcefzPmv7nrQ99LAZy7v3owdWG6SdlgC8E0IeleyKjBDGNcWDaqkvNDCCUri4O5MaM29BivWNO0OnxhQKMio6MQl2R1Fj6pu8ODaGRdHIEaOSkBKj1AqA/FwGOL5MD6mv/fBG0kdGZmhwCVdMm1rIAi2s7QI4MH4YEiyY9zzs=
  app: ht6
  on:
    repo: AlexandrAnash/ht6
