language: node_js
node_js:
- '6'
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: uWS3/MefOBgaWisVZe2VWnw1HAEvyH6S/SxtFvVXXDOMpk8wGDr7NlDLEl5ylN9WW3pMMhAxUXK/K6Qalaw2cXsp6B1ssZMPSSo+oPSZYKIRIeB83nrHLIX+64lz1uNHEuV3jh48ATtfxgW9sHF7SNCqBpuoc+3Fv6OgWEFc3a4ShDefV2Wusy7eRoD0NGrxpxp6ZNnqQ19kvW8AjYFQkSraIT0O+eNZQUpFg6EOgTK7E/GzhUBUVrI7J6iDzaSYjj0//Gi8RDRNeHFkY61M+LkATjaXiY236ZZxJgPM3L8TDK08x+j6M6NNQuwvD4p0N+ZMMRrTFcpw06vcXzW+N7Ixu3MJBK8ytokb6vrFwXZl2wlU0NrfIIfNOd87rOmxtaKit3ZY19TFDskzpUtHFySqY89U9+bQuK5IcbxMcbNkKO/928H+/w+d/w8tnoYFevCx5aDnXmoptrwTcdYeerGtbGZllBf4rQhejWA9ykhfTRJC57VNgFIP5CRjoqZgtiq+SUdVDOcmxE/hrxec6iPvFjijBxvGHiuism74eOx7Fec89MEqwou1Q4Gn3P5HI/nF82ZUChdb7JnG3pY0ayqZMb6xBvn65fiHdnZ8FOvurkGT7ZfOR0AAE8tldqV3B0cvkrH9iKb0ddP+aLxsJNGR5d4SFyR8hm6KZlWuY8I=
  app: ht6
  on:
    repo: AlexandrAnash/ht6
