language: node_js
node_js:
- '6'
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: i7FSsEJUZU9czPBzxGvxDwVb2hjNwnDiLReKbaUiy50Sw+YBdTYEgFviQw8orx7TA9luMgmdHvtFa9TAitT8txdXiISDlF3pOO7usEc3xwsNJxi6nkVQVtO8S2Yx5KH2RxBqoF/2ayt64/3BtGxNOEHH37uQ3v8QlqJG4gjYqsj9z41fdLfdUmwDUvMnobI3TLhAupmgU6f+3IYuxsGguvWWiws1DN1YzO/bPnewUPqr1FJhBH+qTb9ggLD/IHQlDO9YQ5AKflsizA6ELicmXUjyFvwxmj9PFWI9vrmrQrUjsKJt6PKT84RQh70XtiE+CDr5UFSP82UyoND3XKUMwAHzK5xg05XQMGuABQT9m017cw1btn5cdwQs+YDp3zXBMLVU5sxZBalPPXOZkYHBw0IuwYnXKiheT+EqpBqGaMz6UgreqWtWVDr2hBhGQOi2DSJjJ5DMCQnt0enpKhnkPCMb5ZGKMbrnjU6XhCokiJwGPMg17ytKi0EeAJCWl784IH39iNCmmB69iF8RqJ2o9runhYL6Qkhkm7Fpz9n3hy2BCdRZrDMvoICfSC1sV7pu9BSYFya/rjseVlYA3iZTWyQ4DxVeGr91p0a+s9hJ8RmZQoN4YQ387j5mnFZ5FvYC4EmnlEIZMfcSN/qNq8zi7qUjuYvSnFqA+xg36lC5LQQ=
