language: node_js
node_js:
- '6'
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: ND0/swx/cv9VsA5X0+oGu1+NWwzaJnydmifciiJ7L8rKI4JOd/5mcOh7PNfkGKaqyTCG8TxP1rx3b4Yw1Xz662eOkK33q2xDcZ3xGIyuCyuULtxuK8p1BQjNXP/5Ef2DW4DA9wHWQFJz0Vyguue7o626hiTTbYUEVRLWOInkta8aKIiDq4ZxJGw9HACJ3zd2W1407l5cIxpk7xafy+nkPv0i5HhVl/V2twMOX477D52ZaL3mq4qrGAa6Yzcqd8lxjnCxRTxSyZ/81BlSOtwoFnNnr2oLF1m/4gUCisu5UJyLtkU3MoHXS5MqE1olfQjMvcJVhxtaChMnFRz2OgjCuc6LYM0Y96QrHLIyfkid0zt3wkCgU+8sLrJeT/jkg2GtAp4RgZP/tzMtDfaPVwstvqmUNAyM9srgpH/zW5lGnNXBilmZjwTL7FdKqr95ASgS1r+zjsCc31btMjNK08eEmTA+jlgVSwwp8HkOcogvVbBY8agYcn9O6lZO8qeoAqjO8Fq9mRfh2V6z219s5xplSox5lPJdH31QW2O4I6m5J5gP4kDyZCGDmdlbxm+oowvmU/n8/B2Hxp5P8Avomwu0DcQI0+IzGMvO6PgNkRuL3dL8pbM5wzZfrfDPOj24xYRrLEn14BBDj92Xk5h8v81CRJ65Rig9nZbPEw1b0/eeh94=
  app: ht6
  on:
    repo: AlexandrAnash/ht6
