language: node_js
node_js:
- '6'
install:
- npm install
deploy:
  provider: heroku
  app: ht6
  api_key:
    secure: lH+Bp+ed1m/aodGBG9QLaV31nzx2GxxiJ0BNZhFZxu89gI2KDz34a88lRZotumacm2eQFtk7Mwc5nefpqQBBsG9LTO2oXRH9/8lTLZGTF1ZltDLaEAxd1OpT2ypaEkMpM8KSaF4zFoCJlp55UJeEMfSOM2uP5aAnhLRbCgzpeigQA2G72LdA9jxVTIuL7ByzNvt4Adzp6hGf31phIw+S3HUkpz9XqLdoBUV/2NxAVf3hMq8Tj1ZE8HvgOplhVPQACEhBDfn4WOk8tVa99EH6GGKIa6t211QvrKZMbu5gJcqDcHP+VwGjBZZyMzcz5Rt5CLchLXY5SDH5sYnBCi3BRxY8Vtd/iWGrYz4n2t1FbPJE2D83bj0uErXAcgFeRyEmrU2t3RtC0vUcjAbp6o4zLmA8JrdLU0YZRMQRH5CCm0aGX/e8flWlWi/6yD5xIOMElotbANKjAr/IpNTeM2Tp5ztiE84SCPWp8smY9cU1vXDxPWyg32Z0EDE/eQSasbRtyus5us/Nclhp3VleM9cBEXsKq9vXTOwwHBQYUs+NiDsIOnBkCLAQAarYGzVIa7E39nkLCcu+UMsjxkXVOtQUFvPxmiRvh+FPBSQvET1dA+sZhBu9cueNUUmJrIjNrm5Dk7JncqcgjLhERgff6OuY2jyl5ABNPGEMtMdqvL5+a9E=
