language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run test-eslint
deploy:
  provider: heroku
  api_key:
    secure: oHHMnWA30wrouB3UegiSqCNom8ePC7RDJTVipUNr/69WNBTmz82eFAgEkXHY8TUIn0iz+eU/xCdueogD0kZqJ8D7WYZW7ylvo1P5lC2ku0ImxSQhcIEPpywBb8Ri4ZdTFSoOvbVsyXDn2VMRRRnHfprEpxq4ejZRVn9EFHsCo82YQX7EDb9T6mWkLjecBYikQ/UgnzTCzd3bhouMDh2LMbFqA8pwagso0o5eh0wThhTrwgpS3+243PAbtPQy2g83nC5t54wBT1oCdF0N9g+BM7/YWJTkM0rS4opUmX8mcls27uDFo2Cmu2bvRs10ZQ2fewdMlA0US0ltIcevzU4az3bDjX0lZr7mBTw9Oc3dXRQzXYRYc+YbmMNdj4HEPUjMDunmePal+DDToZz7wIm/7fgYhy+a9kqkJKSpXoZRtlMLcxT4+QXb7meERyib+0lMUIyZRlGUmFUN/gxCmC2rqj7VP+geJ+UZEWj0M3X7FjSlGM7UeYj6Df3Agfl1Z4186Lv2YW2EhweDR2kcEm+bEZ7JgYJ1Vq8+Qo2o06u8egJs4Ow8LemOCbTmtrP/zJnhE46F3GmOvFhdoUTqsTpvZiQFqNk5UpPl3yZNmqV3Mh++UEcf01XhxUYsfqPJE4LSRjqhY9tPXhRGEbdt+CM2WWmI/ZwFTgylr0M8U7YMJUk=
  app: ht6
  on:
    repo: AlexandrAnash/ht6
